// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, WxtStorage, WxtStorageItem, StorageArea, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { getAppConfig, useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { fakeBrowser } from 'wxt/testing';
  export { arrayBufferToBase64, base64ToArrayBuffer } from '../utils/audio-encoding';
  export { SelectionRect, SelectionPayload, ModelLoadBroadcastMessage, Message } from '../utils/messages';
  export { broadcastModelLoadProgress, broadcastModelLoadError, ModelLoadBroadcast } from '../utils/model-load-broadcast';
  export { setupOffscreenDocument } from '../utils/offscreen-document';
  export { OFFSCREEN_SYNTHESIZE, OFFSCREEN_WARMUP, OFFSCREEN_STATUS, ensureOffscreenDocument, warmUpOffscreenTts, synthesizeInOffscreen, playAudioInOffscreen, stopAudioInOffscreen, abortOffscreenSynthesis, getOffscreenModelStatus, TtsEngineError, OffscreenSynthResult } from '../utils/offscreen-tts';
  export { tokenizeWords, phraseFromWordRange, WordToken } from '../utils/overlay-phrase';
  export { resetPlaybackClock, stopPlaybackClock, syncPlaybackClock, estimatedPlaybackTimeS, currentLatencyCompensationS } from '../utils/overlay-playback-clock';
  export { overlayWordIndexAtTime } from '../utils/overlay-word-sync';
  export { setOverlayTranslation, highlightOverlayWord, setWordLoadingIndex, setOverlayStatusMessage, updateOverlayProgress, hideOverlay, updatePlaybackState, showOverlay, bindOverlayDismissals, PlaybackState, OverlayState, TranslationViewState } from '../utils/overlay';
  export { clearPageUi } from '../utils/page-ui';
  export { MAX_SELECTION_LENGTH, expandIndicesToWordBoundaries, expandRangeToWordBoundaries, evaluateSelection, getSelectionPayload, SelectionResult } from '../utils/selection';
  export { getTabSession, setTabSession, clearTabSession, TabSessionState } from '../utils/session';
  export { DEFAULT_SETTINGS, getSettings, saveSettings, Voice, Lang, MotSettings } from '../utils/settings';
  export { beginTabRequest, getTabRequestGeneration, isCurrentTabRequest, invalidateTabRequest, clearTabRequest } from '../utils/tab-requests';
  export { hideSelectionToast, showSelectionLimitToast } from '../utils/toast';
  export { WordTiming, TtsAlignment, SynthesizeResult } from '../utils/tts-types';
}
