// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/overlay.js"
    | "/offscreen.html"
    | "/options.html"
    | "/ort/ort-wasm-simd-threaded.jsep.mjs"
    | "/ort/ort-wasm-simd-threaded.jsep.wasm"
    | "/ort/ort-wasm-simd-threaded.mjs"
    | "/ort/ort-wasm-simd-threaded.wasm"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
