// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/overlay.js"
    | "/content-scripts/transcript-edit-guard.js"
    | "/content-scripts/transcript.js"
    | "/icon-128.png"
    | "/icon-16.png"
    | "/icon-24.png"
    | "/icon-48.png"
    | "/icon-96.png"
    | "/offscreen.html"
    | "/options.html"
    | "/ort/ort-wasm-simd-threaded.jsep.mjs"
    | "/ort/ort-wasm-simd-threaded.jsep.wasm"
    | "/ort/ort-wasm-simd-threaded.mjs"
    | "/ort/ort-wasm-simd-threaded.wasm"
    | "/stt/audio-processor.js"
    | "/stt/pkg/stt_wasm_bg.wasm"
    | "/stt/pkg/stt_wasm.js"
    | "/stt/stt-client.js"
    | "/stt/worker.js"
    | "/tesseract/tessdata/fra.traineddata.gz"
    | "/tesseract/tesseract-core-lstm.wasm.js"
    | "/tesseract/tesseract-core-relaxedsimd-lstm.wasm.js"
    | "/tesseract/tesseract-core-relaxedsimd.wasm.js"
    | "/tesseract/tesseract-core-simd-lstm.wasm.js"
    | "/tesseract/tesseract-core-simd.wasm.js"
    | "/tesseract/tesseract-core.wasm.js"
    | "/tesseract/worker.min.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
